{"name": "test_div[zero]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'ZeroDivisionError'", "trace": "self = <pytest_work2.test_cal.TestCal object at 0x03BD3BB0>, get_cal = <pytest_work.calculator.Calculator object at 0x03B9E958>\nget_div_datas = [0, 0, 'ZeroDivisionError']\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_cal, get_div_datas):\n        result = None\n        try:\n            result = get_cal.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_div_datas[2]\nE       AssertionError: assert None == 'ZeroDivisionError'\n\ntest_cal.py:26: AssertionError"}, "attachments": [{"name": "stdout", "source": "fd09d000-cebb-491a-9f58-93ea7a5ec31b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_div_datas", "value": "[0, 0, 'ZeroDivisionError']"}], "start": 1609660308654, "stop": 1609660308655, "uuid": "52fd1a22-cbc2-4ec0-9022-0632defb10e5", "historyId": "9de85392f5d853680024efe50df01c6e", "testCaseId": "38b34d1a75eeb8f446b73885ee1330b3", "fullName": "test_cal.TestCal#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "LAPTOP-HTBK11T2"}, {"name": "thread", "value": "39196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal"}]}